#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-wsdl4j
Version  : 1.6.3
Release  : 2
URL      : https://downloads.sourceforge.net/project/wsdl4j/WSDL4J/1.6.3/wsdl4j-src-1.6.3.zip
Source0  : https://downloads.sourceforge.net/project/wsdl4j/WSDL4J/1.6.3/wsdl4j-src-1.6.3.zip
Source1  : https://repo.maven.apache.org/maven2/wsdl4j/wsdl4j/1.6.3/wsdl4j-1.6.3.jar
Source2  : https://repo.maven.apache.org/maven2/wsdl4j/wsdl4j/1.6.3/wsdl4j-1.6.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : CPL-1.0
Requires: mvn-wsdl4j-data = %{version}-%{release}
Requires: mvn-wsdl4j-license = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : buildreq-mvn

%description
No detailed description available

%package data
Summary: data components for the mvn-wsdl4j package.
Group: Data

%description data
data components for the mvn-wsdl4j package.


%package license
Summary: license components for the mvn-wsdl4j package.
Group: Default

%description license
license components for the mvn-wsdl4j package.


%prep
%setup -q -n wsdl4j-1_6_3

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-wsdl4j
cp license.html %{buildroot}/usr/share/package-licenses/mvn-wsdl4j/license.html
mkdir -p %{buildroot}/usr/share/java/.m2/repository/wsdl4j/wsdl4j/1.6.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/wsdl4j/wsdl4j/1.6.3/wsdl4j-1.6.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/wsdl4j/wsdl4j/1.6.3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/wsdl4j/wsdl4j/1.6.3/wsdl4j-1.6.3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/wsdl4j/wsdl4j/1.6.3/wsdl4j-1.6.3.jar
/usr/share/java/.m2/repository/wsdl4j/wsdl4j/1.6.3/wsdl4j-1.6.3.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-wsdl4j/license.html
